# Generated by Django 4.2.30 on 2026-10-03 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('court_type', models.CharField(choices=[('SUPREME_COURT', 'Supreme Court'), ('HIGH_COURT', 'High Court'), ('DISTRICT_COURT', 'District Court'), ('SUBORDINATE_COURT', 'Subordinate Court'), ('TRIBUNAL', 'Tribunal'), ('OTHER', 'Other')], max_length=30)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('official_identifier', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courts',
                'ordering': ['court_type', 'state', 'name'],
                'indexes': [models.Index(fields=['court_type'], name='courts_court_t_672e09_idx'), models.Index(fields=['state'], name='courts_state_9ab714_idx'), models.Index(fields=['state', 'district'], name='courts_state_8d870e_idx')],
            },
        ),
    ]
