# Generated by Django 4.2.30 on 2026-10-03 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnr_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('case_number', models.CharField(blank=True, max_length=100, null=True)),
                ('case_type', models.CharField(choices=[('CIVIL', 'Civil'), ('CRIMINAL', 'Criminal'), ('WRIT', 'Writ'), ('APPEAL', 'Appeal'), ('REVISION', 'Revision'), ('OTHER', 'Other')], default='CIVIL', max_length=20)),
                ('case_title', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('filing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPOSED', 'Disposed'), ('DECIDED', 'Decided'), ('TRANSFERRED', 'Transferred'), ('ABATED', 'Abated'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('current_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('last_hearing_date', models.DateField(blank=True, null=True)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('data_origin', models.CharField(choices=[('USER_PROVIDED', 'Provided by user'), ('SOURCE_RECORD', 'From an official/source record'), ('DEMO', 'Demo data')], default='USER_PROVIDED', max_length=20)),
                ('is_demo_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='courts.court')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.source')),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hearing_date', models.DateField()),
                ('purpose', models.CharField(blank=True, max_length=300, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('judge', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.case')),
            ],
            options={
                'db_table': 'hearings',
                'ordering': ['-hearing_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_type', models.CharField(choices=[('PETITIONER', 'Petitioner'), ('RESPONDENT', 'Respondent'), ('INTERVENOR', 'Intervenor'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('advocate', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='cases.case')),
            ],
            options={
                'db_table': 'case_parties',
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CASE_FILED', 'Case Filed'), ('NOTICE_ISSUED', 'Notice Issued'), ('HEARING', 'Hearing'), ('ORDER', 'Order'), ('JUDGMENT', 'Judgment'), ('ADJOURNMENT', 'Adjournment'), ('DOCUMENT_FILED', 'Document Filed'), ('STATUS_CHANGE', 'Status Change'), ('OTHER', 'Other')], max_length=20)),
                ('event_date', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('data_origin', models.CharField(choices=[('USER_PROVIDED', 'Provided by user'), ('SOURCE_RECORD', 'From an official/source record'), ('DEMO', 'Demo data')], default='USER_PROVIDED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.source')),
            ],
            options={
                'db_table': 'case_events',
                'ordering': ['event_date'],
            },
        ),
    ]
