# Generated by Django 4.2.30 on 2026-10-03 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['case', 'event_date'], name='case_events_case_id_4b22c4_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['cnr_number'], name='cases_cnr_num_544148_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['user', 'status'], name='cases_user_id_c07d24_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['state', 'district'], name='cases_state_496dce_idx'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(condition=models.Q(('cnr_number__isnull', False)), fields=('user', 'cnr_number'), name='uniq_user_cnr'),
        ),
    ]
