# Generated by Django 4.2.30 on 2026-10-03 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('citation', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('case_number', models.CharField(blank=True, max_length=200, null=True)),
                ('judgment_date', models.DateField(blank=True, null=True)),
                ('bench', models.TextField(blank=True, null=True)),
                ('petitioner', models.CharField(blank=True, max_length=500, null=True)),
                ('respondent', models.CharField(blank=True, max_length=500, null=True)),
                ('legal_topics', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('document_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(default='en', max_length=5)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('embedding_status', models.CharField(choices=[('PENDING', 'Pending'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed'), ('NOT_REQUIRED', 'Not Required')], default='PENDING', max_length=20)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('DEMO', 'Demo Data')], default='UNVERIFIED', max_length=20)),
                ('is_demo_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judgments', to='courts.court')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.source')),
            ],
            options={
                'db_table': 'judgments',
                'ordering': ['-judgment_date'],
                'indexes': [models.Index(fields=['citation'], name='judgments_citatio_e35101_idx'), models.Index(fields=['judgment_date'], name='judgments_judgmen_da6f0d_idx'), models.Index(fields=['state'], name='judgments_state_e60383_idx'), models.Index(fields=['verification_status'], name='judgments_verific_3f63f9_idx')],
            },
        ),
    ]
