# Generated by Django 4.2.30 on 2026-10-03 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_ACCESSED', 'Document Accessed'), ('DOCUMENT_DELETED', 'Document Deleted'), ('AI_REQUEST', 'AI Request'), ('ACTION_PLAN_CREATED', 'Action Plan Created'), ('DRAFT_CREATED', 'Draft Created'), ('CASE_CREATED', 'Case Created'), ('ADMIN_ACTION', 'Admin Action'), ('SOURCE_INGESTED', 'Source Ingested'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_RESET', 'Password Reset'), ('CASE_UPDATED', 'Case Updated'), ('CASE_DELETED', 'Case Deleted'), ('DOCUMENT_ANALYZED', 'Document Analyzed'), ('DOCUMENT_LINK_ISSUED', 'Document Download Link Issued'), ('SEARCH', 'Research Search'), ('ACTION_STEP_UPDATED', 'Action Step Updated'), ('CONVERSATION_DELETED', 'Conversation Deleted'), ('SOURCE_VERIFIED', 'Source Verified'), ('SOURCE_MODIFIED', 'Source Modified'), ('OTHER', 'Other')], max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
