# Generated by Django 4.2.30 on 2026-10-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_ACCESSED', 'Document Accessed'), ('DOCUMENT_DELETED', 'Document Deleted'), ('AI_REQUEST', 'AI Request'), ('ACTION_PLAN_CREATED', 'Action Plan Created'), ('DRAFT_CREATED', 'Draft Created'), ('CASE_CREATED', 'Case Created'), ('ADMIN_ACTION', 'Admin Action'), ('SOURCE_INGESTED', 'Source Ingested'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_RESET', 'Password Reset'), ('CASE_UPDATED', 'Case Updated'), ('CASE_DELETED', 'Case Deleted'), ('DOCUMENT_ANALYZED', 'Document Analyzed'), ('DOCUMENT_LINK_ISSUED', 'Document Download Link Issued'), ('SEARCH', 'Research Search'), ('ACTION_STEP_UPDATED', 'Action Step Updated'), ('CONVERSATION_DELETED', 'Conversation Deleted'), ('SOURCE_VERIFIED', 'Source Verified'), ('SOURCE_MODIFIED', 'Source Modified'), ('AI_CHAT', 'AI Chat'), ('USER_PASSWORD_CHANGE', 'Password Changed'), ('ACTION_PLAN_GENERATED', 'Action Plan Generated'), ('DRAFT_GENERATED', 'Draft Generated'), ('JUDGMENT_EXPLAINED', 'Judgment Explained'), ('OTHER', 'Other')], max_length=40),
        ),
    ]
