# Generated by Django 4.2.30 on 2026-10-03 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('OFFICIAL_COURT', 'Official Court Record'), ('GOVERNMENT', 'Government Source'), ('JUDGMENT', 'Judgment'), ('CASE_RECORD', 'Case Record'), ('USER_DOCUMENT', 'User Uploaded Document'), ('LEGAL_INFORMATION', 'Legal Information'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('court', models.CharField(blank=True, max_length=300, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=300, null=True)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('FAILED', 'Verification Failed'), ('PENDING', 'Pending Verification')], default='UNVERIFIED', max_length=20)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_demo_data', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sources',
                'indexes': [models.Index(fields=['source_type'], name='sources_source__65c870_idx'), models.Index(fields=['verification_status'], name='sources_verific_014b2d_idx'), models.Index(fields=['identifier'], name='sources_identif_7aaa6b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(condition=models.Q(('identifier__isnull', False)), fields=('source_type', 'identifier'), name='uniq_source_type_identifier'),
        ),
    ]
