# Generated by Django 4.2.30 on 2026-10-03 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('situation_assessment', models.TextField()),
                ('delay_cause_analysis', models.TextField(blank=True, null=True)),
                ('immediate_priority', models.TextField(blank=True, null=True)),
                ('warnings', models.JSONField(default=list)),
                ('supporting_sources', models.JSONField(default=list)),
                ('original_query', models.TextField()),
                ('intake_analysis', models.JSONField(default=dict)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(default='en', max_length=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('disclaimer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'action_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('why_relevant', models.TextField(blank=True, null=True)),
                ('documents_needed', models.JSONField(default=list)),
                ('legal_basis', models.CharField(blank=True, max_length=500, null=True)),
                ('estimated_timeline', models.CharField(blank=True, max_length=200, null=True)),
                ('difficulty', models.CharField(default='MEDIUM', max_length=20)),
                ('source_references', models.JSONField(default=list)),
                ('kind', models.CharField(default='POSSIBLE_OPTION', max_length=20)),
                ('source_backed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='action_plans.actionplan')),
            ],
            options={
                'db_table': 'action_steps',
                'ordering': ['action_plan', 'step_number'],
            },
        ),
    ]
