# Generated by Django 4.2.30 on 2026-10-03 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action_plans', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='actionstep',
            unique_together={('action_plan', 'step_number')},
        ),
    ]
