# Generated by Django 4.2.30 on 2026-10-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionstep',
            name='kind',
            field=models.CharField(default='POSSIBLE_OPTION', max_length=30),
        ),
    ]
