# Generated by Django 4.2.30 on 2026-10-03 07:08

from django.db import migrations, models
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('section_title', models.CharField(blank=True, max_length=500, null=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='en', max_length=5)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'knowledge_chunks',
            },
        ),
        migrations.CreateModel(
            name='ResearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField()),
                ('relevance_score', models.FloatField()),
                ('relevance_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'research_results',
                'ordering': ['search_query', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('JUDGMENT', 'Judgment search'), ('SIMILAR_CASE', 'Similar case search'), ('RESEARCH', 'Legal research')], default='JUDGMENT', max_length=20)),
                ('query_text', models.TextField()),
                ('rewritten_queries', models.JSONField(blank=True, default=list)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'search_queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
