# Generated by Django 4.2.30 on 2026-10-03 07:08

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.indexes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judgments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legal_research', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchresult',
            name='judgment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='judgments.judgment'),
        ),
        migrations.AddField(
            model_name='researchresult',
            name='search_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='legal_research.searchquery'),
        ),
        migrations.AddField(
            model_name='researchresult',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='judgment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='judgments.judgment'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='sources.source'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['user', 'created_at'], name='search_quer_user_id_175990_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['state'], name='knowledge_c_state_06c997_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('text', config='simple'), name='kc_text_fts_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='kc_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgechunk',
            unique_together={('source', 'chunk_index')},
        ),
    ]
