# Generated by Django 4.2.30 on 2026-10-03 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('CHAT', 'Chat'), ('INTAKE', 'Intake'), ('DOCUMENT_ASK', 'Document question'), ('DOCUMENT_ANALYZE', 'Document analysis'), ('JUDGMENT_EXPLAIN', 'Judgment explanation'), ('ACTION_PLAN', 'Action plan'), ('SIMILAR_CASES', 'Similar cases')], max_length=20)),
                ('provider', models.CharField(max_length=30)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('prompt_versions', models.JSONField(blank=True, default=dict)),
                ('input_hash', models.CharField(max_length=64)),
                ('input_chars', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='OK', max_length=12)),
                ('error_code', models.CharField(blank=True, max_length=60, null=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('llm_calls', models.PositiveIntegerField(default=0)),
                ('cache_hits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('language', models.CharField(default='en', max_length=5)),
                ('verification_status', models.CharField(default='unverified', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('safety_flags', models.JSONField(blank=True, default=list)),
                ('feedback_rating', models.SmallIntegerField(blank=True, null=True)),
                ('feedback_comment', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_responses',
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
                ('locator', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('VERIFIED', 'Matched a stored source'), ('REJECTED', 'Could not be verified')], max_length=10)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_citations',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(default='en', max_length=5)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai.airesponse')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.conversation')),
            ],
            options={
                'db_table': 'conversation_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
