# Generated by Django 4.2.30 on 2026-10-03 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cases.case'),
        ),
    ]
