# Generated by Django 4.2.30 on 2026-10-03 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_type', models.CharField(choices=[('CASE_SUMMARY', 'Case Summary'), ('LAWYER_BRIEF', 'Lawyer Brief'), ('RTI_APPLICATION', 'RTI Application'), ('GENERAL_APPLICATION', 'General Application')], max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('content_english', models.TextField()),
                ('content_hindi', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=5)),
                ('placeholders_used', models.JSONField(default=list)),
                ('field_provenance', models.JSONField(default=dict)),
                ('source_references', models.JSONField(default=list)),
                ('filing_instructions', models.TextField(blank=True, null=True)),
                ('important_notes', models.JSONField(default=list)),
                ('source_intake', models.JSONField(default=dict)),
                ('disclaimer', models.TextField(default='This draft is generated for informational purposes only. It is NOT a legally valid filing. Verify all details with a qualified legal professional before use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='cases.case')),
            ],
            options={
                'db_table': 'generated_drafts',
                'ordering': ['-created_at'],
            },
        ),
    ]
